version: '3'
services:
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - mlc_redis_data:/data
    restart: always

volumes:
  mlc_redis_data: