name: 'Create Pull Request'

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main' # Ветка, в которую вы хотите сделать pull request
          github_token: ${{ secrets.GITHUB_TOKEN }} # подставляется автоматом
          pr_title: 'New changes from Develop' # Заголовок для pull request
          pr_body: 'Create Pull Request' # Содержание сообщения pull request
